spring.application.name=pdf-rag
spring.ai.google.genai.api-key=${GENAI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
logging.level.org.springframework.ai.chat.client.advisor=debug
spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=rag-index
spring.ai.vectorstore.pinecone.namespace=user1

